package consts

// Major categories
const (
	BaseURL           = "https://api.themoviedb.org/3"
	AltURL            = "https://api.tmdb.org/3"
	DetailsURL        = "/account"
	AuthenticationURL = "/authentication"
	CertificationURL  = "/certification"
	CollectionURL     = "/collection"
	CompanyURL        = "/company"
	ConfigurationURL  = "/configuration"
	CreditURL         = "/credit"
	DiscoverURL       = "/discover"
	FindURL           = "/find"
	GenreURL          = "/genre"
	GuestSessionURL   = "/guest_session"
	KeywordURL        = "/keyword"
	ListURL           = "/list"
	MovieURL          = "/movie"
	NetworkURL        = "/network"
	PersonURL         = "/person"
	ReviewURL         = "/review"
	SearchURL         = "/search"
	SeasonURL         = "/season"
	TrendingURL       = "/trending"
	WatchURL          = "/watch"
)

// Sub-Categories
const (
	AccountStatesURL        = "/account_states"
	AddMovieURL             = "/add_item"
	AggregateCreditsURL     = "/aggregate_credits"
	AiringTodayURL          = "/airing_today"
	AllURL                  = "/all"
	AltNamesURL             = "/alternative_names"
	AltTitlesURL            = "/alternative_titles"
	AvailableRegionsURL     = "/regions"
	ChangesURL              = "/changes"
	ClearURL                = "/clear"
	CombinedCreditsURL      = "/combined_credits"
	ContentRatingsURL       = "/content_ratings"
	ConvertURL              = "/convert"
	CountriesURL            = "/countries"
	CreateNewURL            = "/new"
	CreditsURL              = "/credits"
	EpisodeGroupsURL        = "/episode_groups"
	EpisodeGroupURL         = "/episode_group"
	EpisodesURL             = "/episodes"
	EpisodeURL              = "/episode"
	ExternalIdURL           = "/external_ids"
	FavoriteURL             = "/favorite"
	ImagesURL               = "/images"
	ItemStatusURL           = "/item_status"
	JobsURL                 = "/jobs"
	LanguagesURL            = "/languages"
	LatestURL               = "/latest"
	ListsURL                = "/lists"
	MovieCreditsURL         = "/movie_credits"
	MoviesURL               = "/movies"
	MultiURL                = "/multi"
	NowPlayingURL           = "/now_playing"
	OnTheAirURL             = "/on_the_air"
	PopularURL              = "/popular"
	PrimaryTranslationsURL  = "/primary_translations"
	ProvidersURL            = "/providers"
	RatedURL                = "/rated"
	RatingURL               = "/rating"
	RecommendationURL       = "/recommendations"
	ReleaseDatesURL         = "/release_date"
	RemoveMovieURL          = "/remove_item"
	ReviewsURL              = "/reviews"
	ScreenedTheatricallyURL = "/screened_theatrically"
	SessionURL              = "/session"
	SessionWithLoginURL     = "/validate_with_login"
	SimilarURL              = "/similar"
	TimezonesURL            = "/timezones"
	TokenURL                = "/token"
	TopRatedURl             = "/top_rated"
	TranslationsURL         = "/translations"
	TvCreditsURL            = "/tv_credits"
	TvURL                   = "/tv"
	UpcomingURL             = "/upcoming"
	V4URL                   = "/4"
	VideosURL               = "/videos"
	WatchlistURL            = "/watchlist"
)

// Deprecated Calls
const (
	TaggedImagesURL = "/tagged_images"
)

// Queries
const (
	QueryURL = "?query="
	PageURL  = "&page="
	LangURL  = "&language="
	IncludeAdult
	KeywordQuery = "&keyword="
	StartDateURL = "&start_date="
	EndDateURL   = "&end_date="
)

// TODO: Properly name these sections
